/* ============================================================
   QUEM TREINA NA ESTRADA
   Um por linha de rota, com a classe que os jogos dariam pra ele
   e o rosto da classe. `times` são os quatro escalões (0–1, 2–3,
   4–5, 6–8 insígnias), sempre com a forma final pedida: quem
   decide a forma no nível é formaAteONivel, então um Pidgeot no
   escalão de baixo sai Pidgey. `reserva` é o que entra no lugar
   de parte do time, sorteado a cada luta.

   `abre` é a primeira vez; `volta`, quando ele te para de novo
   num escalão novo; `perde` e `vence`, o que ele diz no fim.
   Quem tem `numero` passa o número na primeira derrota — e vira
   contato no PokéNav (pokenav.js lê esta lista).

   Os nomes são os dos treinadores de rota de Red/Blue e FireRed,
   pela regra do projeto: internacional, curto, de ler em voz alta.
   ============================================================ */
const TREINADORES_ESTRADA = [

/* ── Quem fecha caminho (barreiras.js): não para ninguém na estrada,
      espera onde está; só luta quem vai até lá ─────────────────── */
{id:'roque_tunel', local:'rota9', classe:'Caçador', arq:'roughneck', artigo:'um', nome:'Roque', barreira:true, dif:2,
 times:[[23,41], [24,42,20], [24,42,20,49], [24,42,20,49,110]], reserva:[48,88],
 abre:'"Você é {o|a} da floresta." Ele não levanta da pedra. "A gente tem memória boa pra rosto. Quer passar, passa por cima."',
 volta:'"De novo? Tá. A gente tem o dia inteiro."',
 perde:'"Passa." Ele guarda a Pokébola sem olhar pra ela. "Mas a gente anotou de novo."',
 vence:'"Volta por Saffron, {garoto|garota}. É mais longe e é mais seguro. Pra você."'},
{id:'brutus_ciclovia', local:'celadon', classe:'Segurança', arq:'roughneck', artigo:'um', nome:'Brutus', barreira:true, dif:2,
 times:[[52,58], [53,58,66], [53,59,67,110], [53,59,68,110,112]], reserva:[57,24],
 abre:'"O cassino tem uma lista. Você está nela." Ele estala o pescoço. "Mas eu sou um homem razoável. Ganha de mim e eu perco a lista."',
 volta:'"Voltou pra apanhar com educação. Respeito isso."',
 perde:'"Pode passar. E não pisa mais no tapete do cassino, que eu não perco duas vezes a mesma lista."',
 vence:'"A Ciclovia continua fechada pra você. Vai por Lavender, que lá ninguém liga."'},

/* ── Rota 1 ─────────────────────────────────────────────── */
{id:'joey', local:'rota1', classe:'Garoto', arq:'youngster', artigo:'um', nome:'Joey',
 times:[[19], [19,16], [16,21,20], [17,22,84,20]], reserva:[161,21],
 abre:'"Ei! Você! O meu Rattata não é um Rattata qualquer. Ele tá entre os melhores Rattata que existem. Eu posso provar."',
 volta:'"Voltou! O meu Rattata treinou. Ele continua entre os melhores. Talvez agora um pouco mais entre."',
 perde:'"Tá. Tá bom. Ele ainda tá entre os melhores. Você que tá entre os melhores de outra coisa."',
 vence:'"Viu? Eu falei. Entre os melhores."',
 numero:{passa:'Joey escreve o número na palma da sua mão com caneta, porque não tem papel. "Me liga. Eu vou ter novidade do Rattata."',
   oferece:['revanche','prova'],
   prova:{rotulo:'Perguntar do Rattata',
     texto:[
       '"Ele comeu uma coisa estranha ontem e ficou bem. Isso é sinal de força, né?"',
       '"Eu vou treinar ele até o fim do mês. Aí você vai ver."'
     ]}}},
{id:'crissy', local:'rota1', classe:'Garota', arq:'lass', artigo:'uma', nome:'Crissy',
 times:[[16], [16,43], [17,44,35], [18,45,36,39]], reserva:[187,174],
 abre:'"Primeira luta do dia! A gente tá na Rota 1, então a regra é pegar leve. Mais ou menos leve."',
 volta:'"Você de novo? Agora eu não pego leve nada."',
 perde:'"Eu não peguei leve. Eu só perdi mesmo."',
 vence:'"Rota 1 também é estrada, {moço|moça}."'},

/* ── Rota 22 ────────────────────────────────────────────── */
{id:'shane', local:'rota22', classe:'Campista', arq:'camper', artigo:'um', nome:'Shane',
 times:[[56,21], [56,27,21], [57,28,22,66], [57,28,22,67,111]], reserva:[74,231],
 abre:'"Eu venho aqui todo dia olhar o portão. Um dia eu passo por ele. Hoje eu treino em você."',
 volta:'"O portão continua lá, e eu continuo aqui. Só que mais forte."',
 perde:'"Oito insígnias. Eu tô tão longe que chega a ser engraçado."',
 vence:'"Quem quer o portão tem que passar por mim primeiro. É o que eu digo pra mim mesmo."'},
{id:'naomi', local:'rota22', classe:'Treinadora Ás', arq:'ace_trainer_f', artigo:'uma', nome:'Naomi', dif:2,
 times:[[29,43], [30,44,118], [30,44,119,77], [31,45,119,78,131]], reserva:[183,179],
 abre:'"Eu passei pelo portão. Voltei pra treinar quem ainda não passou. Quer ver o que tem do outro lado?"',
 volta:'"Você cresceu. Eu reparo nisso, é meu trabalho."',
 perde:'"Boa. Guarda esse jeito de mandar. Lá em cima ele vale mais do que qualquer Pokémon."',
 vence:'"Do outro lado do portão é assim o tempo todo. Descansa e volta."',
 numero:{passa:'Naomi te dá o número escrito atrás de um recibo de Centro Pokémon. "Me liga quando tiver mais uma insígnia. Eu gosto de ver o placar mudar."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Pedir um conselho de luta', limite:3, esperaCap:3,
     texto:[
       '"Conselho? Tá. Troca antes de cair, não depois. Quem troca depois já perdeu o turno."',
       '"E cura no Centro mesmo quando acha que não precisa. Principalmente quando acha que não precisa."'
     ],
     efeito:d=>{ Estado.darItem('Super Potion', 2); return [{tipo:'item', texto:'Ela deixa 2× Super Potion no balcão do Centro mais próximo, no seu nome.'}]; }}}},

/* ── Rota 2 ─────────────────────────────────────────────── */
{id:'rick', local:'rota2', classe:'Caçador de Insetos', arq:'bug_catcher', artigo:'um', nome:'Rick',
 times:[[10,13], [11,14,165], [12,15,166,48], [12,15,168,49,123]], reserva:[167,46,193],
 abre:'"Esse corredor é o melhor lugar de Kanto pra inseto e ninguém sabe. Agora você sabe. Luta comigo pra eu ter certeza de que você merece saber."',
 volta:'"Os meus casularam, abriram e voltaram pra lutar. Olha só."',
 perde:'"Inseto perde. Depois inseto vira outra coisa. Espera pra ver."',
 vence:'"Rede, pote e paciência. É só isso."'},

/* ── Floresta de Viridian ───────────────────────────────── */
{id:'doug', local:'floresta', classe:'Caçador de Insetos', arq:'bug_catcher', artigo:'um', nome:'Doug',
 times:[[13,10], [14,11,46], [15,12,47,165], [15,12,47,166,127]], reserva:[204,167],
 abre:'"Shhh. Tá ouvindo? Não? É porque eles pararam quando você chegou. Agora você me deve uma luta."',
 volta:'"Eles voltaram a cantar. E eu voltei a querer te bater."',
 perde:'"Tudo bem. A floresta não liga pra quem ganha."',
 vence:'"A floresta é minha casa. Aqui eu não perco pra visita."',
 numero:{passa:'Doug te dá o número e pede pra não ligar de noite. "De noite eu tô ouvindo."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Perguntar o que a floresta anda dando', limite:4, esperaCap:2,
     texto:[
       '"Esses dias tá dando Poké Ball perdida. Gente passa correndo e deixa cair."',
       '"Eu junto e guardo. Não é minha, mas também não é de ninguém mais."'
     ],
     efeito:d=>{ Estado.darItem('Poké Ball', 3); return [{tipo:'item', texto:'Ele manda 3× Poké Ball pelo Centro. "Achado não é roubado. Achado é achado."'}]; }}}},
{id:'sammy', local:'floresta', classe:'Caçador de Insetos', arq:'bug_catcher', artigo:'um', nome:'Sammy',
 times:[[10,13,10], [11,14,167], [12,15,168,193], [12,15,168,205,214]], reserva:[46,48,165],
 abre:'"Cuidado onde pisa! Tem Weedle aqui. Tem Weedle em todo lugar. Luta comigo que eu te mostro qual é qual."',
 volta:'"Eu tava contando quantos passaram por aqui hoje. Você é o décimo nono. Luta?"',
 perde:'"Perder pra quem sabe onde pisa é justo."',
 vence:'"Olha o chão, {moço|moça}. Olha sempre o chão."'},
{id:'anthony', local:'floresta', classe:'Garoto', arq:'youngster', artigo:'um', nome:'Anthony',
 times:[[16,19], [16,19,43], [17,20,44,25], [18,20,45,26,22]], reserva:[161,163],
 abre:'"Eu me perdi aqui dentro faz duas horas e não vou admitir. Luta comigo que ninguém repara."',
 volta:'"Não me perdi hoje. Quase. Luta?"',
 perde:'"Agora eu tô perdido E derrotado."',
 vence:'"Pelo menos isso. Você sabe o caminho pra Pewter?"'},

/* ── Rota 3 ─────────────────────────────────────────────── */
{id:'ben', local:'rota3', classe:'Garoto', arq:'youngster', artigo:'um', nome:'Ben',
 times:[[19,23], [20,23,21], [20,24,22,32], [20,24,22,34,207]], reserva:[27,161],
 abre:'"Eu gosto de short. Short é confortável. E luta de short é mais rápida."',
 volta:'"Ainda de short. Ainda rápido."',
 perde:'"Nem o short salvou."',
 vence:'"Short, {moço|moça}. Pensa nisso."'},
{id:'janice', local:'rota3', classe:'Garota', arq:'lass', artigo:'uma', nome:'Janice',
 times:[[16,29], [16,30,39], [17,30,40,183], [18,31,40,184,36]], reserva:[35,187],
 abre:'"Você olhou pra mim! Na estrada isso quer dizer que a gente vai lutar. Eu não inventei a regra."',
 volta:'"Olhou de novo. Regra é regra."',
 perde:'"Da próxima eu olho pro outro lado."',
 vence:'"Regra é regra, e eu cumpro direitinho."'},
{id:'calvin', local:'rota3', classe:'Montanhista', arq:'hiker', artigo:'um', nome:'Calvin',
 times:[[74,66], [74,66,95], [75,67,95,111], [76,68,208,112,185]], reserva:[27,231,213],
 abre:'"Subindo pro Monte da Lua? Primeiro esquenta as pernas com uma luta."',
 volta:'"Voltou inteiro da montanha. Agora você aguenta pedra de verdade."',
 perde:'"Hohoho. Você tem joelho bom."',
 vence:'"Montanha ensina. Às vezes ensina doendo."',
 numero:{passa:'Calvin anota o número com um toco de lápis. "Se você ficar preso numa caverna, me liga. Eu conheço todas."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Perguntar o que ele achou nas pedras', limite:3, esperaCap:3,
     texto:[
       '"Achei uma coisa que brilha no fundo de uma fenda. Não sei o que é. Você que sabe dessas coisas."',
       '"Deixei no Centro pra você. Se for pedra comum, pelo menos é bonita."'
     ],
     efeito:d=>{ const pedra = Dados.escolher(['Moon Stone','Pedra do Trovão','Pedra da Folha']);
       Estado.darItem(pedra, 1); return [{tipo:'item', texto:`Ele deixou uma ${pedra} no balcão do Centro, no seu nome.`}]; }}}},

/* ── Monte da Lua ───────────────────────────────────────── */
{id:'miriam', local:'monte_lua', classe:'Garota', arq:'lass', artigo:'uma', nome:'Miriam',
 times:[[35,39], [35,39,41], [35,40,42,173], [36,40,169,176,35]], reserva:[174,183],
 abre:'"Dizem que Clefairy dança aqui dentro na lua cheia. Eu vim ver. Enquanto não dança, eu luto."',
 volta:'"Ainda não vi a dança. Mas vi você de novo."',
 perde:'"Talvez a dança seja pra quem ganha."',
 vence:'"Pode ser que hoje dance. Fica pra ver?"'},
{id:'jovan', local:'monte_lua', classe:'Nerd', arq:'super_nerd', artigo:'um', nome:'Jovan',
 times:[[81,100], [81,100], [82,101,89,137], [82,101,89,233,110]], reserva:[88,109],
 abre:'"Eu tô medindo o campo magnético da caverna. Você interferiu nas minhas leituras. Agora vai ter que interferir numa luta."',
 volta:'"Leituras novas, time novo. Método científico."',
 perde:'"Dado inconclusivo. Preciso repetir o experimento."',
 vence:'"Previsível. Eu tinha anotado que ia ser assim."',
 numero:{passa:'Jovan te passa um cartão de visita feito à mão, com o número e três equações que não têm nada a ver com nada.',
   oferece:['revanche','prova'],
   prova:{rotulo:'Contar quantas espécies você registrou',
     texto:d=>[
       `"${Estado.contagemDex().catalogados} espécies catalogadas?" Você ouve ele digitando. "Isso dá uma curva interessante."`,
       '"Continua. Eu tô fazendo um gráfico de você. No bom sentido."'
     ]}}},
{id:'marcos', local:'monte_lua', classe:'Montanhista', arq:'hiker', artigo:'um', nome:'Marcos',
 times:[[74,41], [74,41,95], [75,42,95,27], [76,169,208,28,213]], reserva:[46,50],
 abre:'"Tá escuro, eu sei. Luta no escuro é mais honesta, ninguém se exibe."',
 volta:'"Voltou pro escuro? Bom sinal."',
 perde:'"Hoho. Você enxerga bem aqui dentro."',
 vence:'"Caverna é minha sala de estar."'},

/* ── Rota 4 ─────────────────────────────────────────────── */
{id:'robin', local:'rota4', classe:'Garota', arq:'lass', artigo:'uma', nome:'Robin',
 times:[[29,16], [30,17,43], [30,17,44,183], [31,18,45,184,36]], reserva:[39,187],
 abre:'"Desceu do monte agora? Então tá cansad{o|a}. Perfeito pra mim."',
 volta:'"Dessa vez você não tá cansad{o|a}. Eu também não."',
 perde:'"Pelo jeito cansad{o|a} você luta melhor."',
 vence:'"Descansa em Cerulean, que o rio faz bem."'},
{id:'cale', local:'rota4', classe:'Campista', arq:'camper', artigo:'um', nome:'Cale',
 times:[[27,23], [27,23,50], [28,24,51,105], [28,24,51,105,232]], reserva:[104,231],
 abre:'"Tô acampado aqui há três dias esperando alguém pra lutar. Três dias! Por favor, não recusa."',
 volta:'"Quatro dias dessa vez. Obrigado por voltar."',
 perde:'"Valeu a espera."',
 vence:'"Valeu a espera, e ainda ganhei."'},

/* ── Rota 24 / 25 ───────────────────────────────────────── */
{id:'haley', local:'rota24', classe:'Garota', arq:'lass', artigo:'uma', nome:'Haley',
 times:[[43,16,19], [44,17,60], [44,17,61,183], [45,18,62,184,182]], reserva:[187,191],
 abre:'"A ponte tem regra: quem atravessa, luta. Eu sou a terceira da fila. Não reclama."',
 volta:'"A regra da ponte continua valendo pra quem volta."',
 perde:'"Pode passar. Passou bonito."',
 vence:'"Volta pro começo da ponte e tenta de novo."'},
{id:'timmy', local:'rota24', classe:'Garoto', arq:'youngster', artigo:'um', nome:'Timmy',
 times:[[23,21,19], [23,21,20,56], [24,22,20,57], [24,22,20,57,207]], reserva:[161,32],
 abre:'"Eu sou o quarto da ponte. O mais forte! Mentira, o mais novo. Mas luta mesmo assim."',
 volta:'"Eu subi pra terceiro da fila. Treinei."',
 perde:'"Quarto da ponte de novo."',
 vence:'"Eu falei que era o mais forte!"'},
{id:'flint', local:'rota24', classe:'Campista', arq:'camper', artigo:'um', nome:'Flint',
 times:[[58,19], [58,20,54], [59,20,55,77], [59,20,55,78,229]], reserva:[228,37],
 abre:'"Fogueira de beira de rio é a melhor que tem. Senta aqui depois. Antes, luta."',
 volta:'"A fogueira ainda tá acesa. Eu nunca deixo apagar."',
 perde:'"Senta. Tem chá."',
 vence:'"Fogo e água na mesma margem. Eu ganho de quem só trouxe um."'},
{id:'kelsey', local:'rota24', classe:'Campista', arq:'picnicker', artigo:'uma', nome:'Kelsey',
 times:[[60,118], [61,118,183], [61,119,184,79], [62,119,184,80,186]], reserva:[194,54],
 abre:'"Eu pesco, eu nado, eu luto. Nessa ordem. Agora é a última."',
 volta:'"Voltou pra beira? A água tava fria hoje, mas eu tô quente."',
 perde:'"Volto pra pesca."',
 vence:'"Água é meu lado do campo."',
 numero:{passa:'Kelsey anota o número numa folha de caderno molhada. "Se o rio subir, eu aviso. Eu sempre sei antes."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Perguntar como está o rio', limite:3, esperaCap:2,
     texto:[
       '"Tá baixo. Quando tá baixo aparece Poké Ball de gente que derrubou da ponte."',
       '"Eu pesquei duas. Uma é sua, pelo trabalho de ter perguntado."'
     ],
     efeito:d=>{ Estado.darItem('Great Ball', 2); return [{tipo:'item', texto:'Ela manda 2× Great Ball pelo Centro, ainda úmidas.'}]; }}}},

/* ── Rota 9 / 10 ────────────────────────────────────────── */
{id:'alicia', local:'rota9', classe:'Campista', arq:'picnicker', artigo:'uma', nome:'Alicia',
 times:[[43,29], [44,30,39], [44,30,40,179], [45,31,40,181,182]], reserva:[187,209],
 abre:'"Ninguém gosta dessa rota. Eu gosto. Então ela é minha, e quem passa luta."',
 volta:'"Ainda minha. Ainda luta."',
 perde:'"Pode passar pela minha rota."',
 vence:'"Minha rota, minha vitória."'},
{id:'alan', local:'rota9', classe:'Montanhista', arq:'hiker', artigo:'um', nome:'Alan',
 times:[[74,95], [75,95,66], [75,95,67,111], [76,208,68,112,232]], reserva:[27,219],
 abre:'"Sente o cheiro? Tomada queimada. Ninguém sabe de onde vem. Eu parei de me perguntar e comecei a treinar."',
 volta:'"O cheiro continua. Eu também."',
 perde:'"Rapaz. Você tem braço."',
 vence:'"Pedra sobre pedra, {moço|moça}."'},
{id:'chris', local:'rota9', classe:'Campista', arq:'camper', artigo:'um', nome:'Chris',
 times:[[56,27], [56,28,66], [57,28,67,106], [57,28,68,107,237]], reserva:[236,207],
 abre:'"Eu treino luta. Luta de verdade, de soco. Mas os meus Pokémon lutam melhor que eu, então vai com eles."',
 volta:'"Soco novo. Quer ver?"',
 perde:'"Bom soco. O seu, não o meu."',
 vence:'"Soco, esquiva, soco."',
 numero:{passa:'Chris te dá o número e aperta a sua mão forte demais. "Liga quando quiser treinar. Eu nunca tô ocupado."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Chamar pra treinar junto', limite:3, esperaCap:3,
     texto:[
       '"Treino? Vem. Eu tô na mesma pedra de sempre."',
       '"Vocês passam uma tarde repetindo a mesma coisa até ele desistir antes de você. Ninguém ganha e todo mundo melhora."'
     ],
     efeito:d=>{ const p = Estado.primeiroApto(); if (!p) return [];
       const ev = ganharExp(p, 120 + numInsignias() * 60);
       return [{tipo:'info', texto:`${nomeExib(p)} voltou do treino mais dur${pron(p).o}.`}]; }}}},

/* ── Túnel da Rocha ─────────────────────────────────────── */
{id:'ashton', local:'tunel_rocha', classe:'Pokémaníaco', arq:'pokemaniac', artigo:'um', nome:'Ashton',
 times:[[104,79], [104,79,111], [105,80,112,108], [105,199,112,108,115]], reserva:[206,131],
 abre:'"No escuro eu não vejo os seus, mas eu ouço. Pelo barulho eu já sei três. Luta pra eu descobrir o resto."',
 volta:'"Eu reconheço o barulho dos seus. Cresceram."',
 perde:'"Ahh, que time. Que time! Posso ouvir de novo?"',
 vence:'"Os meus são raros. Isso ajuda."',
 numero:{passa:'Ashton te passa o número no escuro e você só descobre que está de cabeça pra baixo no papel quando sai do túnel.',
   oferece:['revanche','prova'],
   prova:{rotulo:'Contar de um Pokémon raro que você viu',
     texto:[
       '"Onde? Quando? Que horas? De que lado ele estava?"',
       '"Não precisa me dizer. Mentira, precisa. Eu vou anotar tudo."'
     ]}}},
{id:'leah', local:'tunel_rocha', classe:'Campista', arq:'picnicker', artigo:'uma', nome:'Leah',
 times:[[41,35], [41,35,74], [42,35,75,200], [169,36,75,200,215]], reserva:[92,46],
 abre:'"Eu tô aqui há uma hora esperando a lanterna voltar a funcionar. Enquanto isso, luta."',
 volta:'"Trouxe pilha dessa vez. Mas ainda quero lutar."',
 perde:'"Me acompanha até a saída?"',
 vence:'"No escuro eu luto melhor. Não sei por quê."'},
{id:'lenny', local:'tunel_rocha', classe:'Montanhista', arq:'hiker', artigo:'um', nome:'Lenny', dif:1,
 times:[[74,66,95], [75,67,95], [75,67,95,112], [76,68,208,112,248]], reserva:[213,185],
 abre:'"Quem entra aqui sem lanterna é doido. Quem entra com lanterna e luta comigo é corajoso."',
 volta:'"Corajos{o|a} de novo, hein."',
 perde:'"Tá bom. Pode ir. Olha a cabeça na terceira curva."',
 vence:'"Olha a cabeça na terceira curva, sempre."'},

/* ── Rota 5 ─────────────────────────────────────────────── */
{id:'reli', local:'rota5', classe:'Garota', arq:'lass', artigo:'uma', nome:'Reli',
 times:[[52,39], [52,39,209], [53,40,210,176], [53,40,210,176,241]], reserva:[35,190],
 abre:'"Asfalto do começo ao fim, que tédio. Me distrai com uma luta?"',
 volta:'"Ainda tédio. Me distrai de novo."',
 perde:'"Pelo menos passou o tempo."',
 vence:'"Distraiu. Obrigada."'},
{id:'kent', local:'rota5', classe:'Paranormal', arq:'psychic', artigo:'um', nome:'Kent',
 times:[[63,96], [63,96,177], [64,97,178,122], [65,97,178,122,203]], reserva:[79,202],
 abre:'"Eu sabia que você vinha. Não é truque. Tem uma placa de Saffron logo ali e todo mundo que vem daqui vai pra lá."',
 volta:'"Eu sabia que você ia voltar. Isso sim foi truque."',
 perde:'"Esse eu não previ."',
 vence:'"Previsto."'},

/* ── Rota 6 ─────────────────────────────────────────────── */
{id:'ricky', local:'rota6', classe:'Campista', arq:'camper', artigo:'um', nome:'Ricky',
 times:[[7,19], [8,20,54], [8,20,55,98], [9,20,55,99,230]], reserva:[183,60],
 abre:'"O riacho corta a trilha três vezes. Na terceira eu sempre luto. Essa é a terceira."',
 volta:'"Terceira travessia de novo."',
 perde:'"Vai, atravessa."',
 vence:'"A terceira é minha."'},
{id:'nancy', local:'rota6', classe:'Campista', arq:'picnicker', artigo:'uma', nome:'Nancy',
 times:[[16,43], [17,44,187], [17,44,188,183], [18,182,189,184,17]], reserva:[191,69],
 abre:'"Piquenique na beira da ponte e ainda aparece treinador. Hoje tá bom demais."',
 volta:'"Piquenique de novo! Luta de novo!"',
 perde:'"Pega um bolinho. Perder dá fome."',
 vence:'"Pega um bolinho mesmo assim."',
 numero:{passa:'Nancy anota o número num guardanapo. "Quando eu fizer outro piquenique eu te ligo. Eu faço muitos."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Perguntar do próximo piquenique', limite:4, esperaCap:2,
     texto:[
       '"Domingo! Mentira, eu não sei que dia é. Mas eu mandei comida pro Centro, no seu nome."',
       '"É ração que sobrou do meu. Os meus comem, os seus também vão comer."'
     ],
     efeito:d=>{ Estado.darItem('Ração', 2); Estado.darItem('Potion', 2);
       return [{tipo:'item', texto:'Chegou no Centro: 2× Ração e 2× Potion embrulhados em pano xadrez.'}]; }}}},
{id:'jeff', local:'rota6', classe:'Caçador de Insetos', arq:'bug_catcher', artigo:'um', nome:'Jeff',
 times:[[10,48], [11,48,165], [12,49,166,127], [12,49,212,127,214]], reserva:[123,46],
 abre:'"Achei um Venonat que brilha no escuro. Mentira. Mas ele é bom. Luta?"',
 volta:'"Ainda não brilha. Ainda é bom."',
 perde:'"Inseto não desiste. Eu às vezes."',
 vence:'"Pode chamar de Venonat de ouro."'},

/* ── Rota 7 ─────────────────────────────────────────────── */
{id:'jasper', local:'rota7', classe:'Apostador', arq:'gambler', artigo:'um', nome:'Jasper',
 times:[[52,109], [52,109,58], [53,110,59,100], [53,110,59,101,137]], reserva:[96,229],
 abre:'"Aposto que eu ganho. Aposto em mim sempre. Dá errado muito, mas quando dá certo compensa."',
 volta:'"Aposta nova. Mesmo favorito."',
 perde:'"Perdi a aposta. Perdi muitas hoje."',
 vence:'"Pagou quatro pra um!"'},
{id:'lola', local:'rota7', classe:'Beldade', arq:'beauty', artigo:'uma', nome:'Lola',
 times:[[37,133], [37,133,39], [38,134,40,36], [38,196,40,36,241]], reserva:[135,136,197],
 abre:'"Fila pra Celadon. Fila pra Saffron. Eu fico no meio, lutando com quem passa. É mais divertido que fila."',
 volta:'"Voltou pra fila? Então luta."',
 perde:'"Você é mais interessante que a fila."',
 vence:'"A fila andou. Você não."'},

/* ── Rota 8 ─────────────────────────────────────────────── */
{id:'glenn', local:'rota8', classe:'Nerd', arq:'super_nerd', artigo:'um', nome:'Glenn',
 times:[[88,109], [88,109,81], [89,110,82,101], [89,110,82,101,233]], reserva:[100,137],
 abre:'"Rota reta, sem graça, perfeita pra pensar. Eu tava pensando em você chegando. E você chegou."',
 volta:'"Pensei em você de novo. Estatisticamente você ia voltar."',
 perde:'"Refaço as contas."',
 vence:'"As contas bateram."'},
{id:'paige', local:'rota8', classe:'Garota', arq:'lass', artigo:'uma', nome:'Paige',
 times:[[35,43], [35,44,183], [35,44,184,209], [36,45,184,210,176]], reserva:[39,173],
 abre:'"Eu detesto essa rota. Luta comigo que ela passa mais rápido."',
 volta:'"Ainda detesto. Luta de novo."',
 perde:'"Passou rápido pelo menos."',
 vence:'"Até que a rota ficou boa agora."'},
{id:'jaren', local:'rota8', classe:'Motoqueiro', arq:'biker', artigo:'um', nome:'Jaren',
 times:[[109,88], [109,88,23], [110,89,24,58], [110,89,24,59,229]], reserva:[41,52],
 abre:'"A rota é reta. Reta é pra correr. Mas hoje eu parei, e quem me fez parar vai lutar."',
 volta:'"Parei de novo por sua causa."',
 perde:'"Tá, tá. Vou correr pra esquecer."',
 vence:'"Fumaça no seu olho."'},
{id:'ethel', local:'rota8', classe:'Médium', arq:'medium', artigo:'uma', nome:'Ethel',
 times:[[92,92], [92,93,200], [93,93,200,105], [94,93,200,105,198]], reserva:[104,92],
 abre:'"Venho de Lavender a pé. Todo dia. Os que eu levo comigo gostam de andar. Eles querem lutar com você."',
 volta:'"Eles lembraram de você. Eles lembram de tudo."',
 perde:'"Eles estão satisfeitos. Eu também."',
 vence:'"Eles pediram pra te dizer que foi uma boa luta."',
 numero:{passa:'Ethel escreve o número a lápis num papel de vela. "Se você passar por Lavender, liga. Eu faço chá."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Perguntar como estão os dela', limite:3, esperaCap:3,
     texto:[
       '"Calmos. Calmo é bom. Calmo é quando eles estão perto."',
       '"Eu mandei uma coisa pra você. Não abre com pressa."'
     ],
     efeito:d=>{ Estado.darItem('Full Heal', 2); Estado.darItem('Revive', 1);
       return [{tipo:'item', texto:'Chegou no Centro um pacote com cheiro de incenso: 2× Full Heal e 1× Revive.'}]; }}}},

/* ── Rota 11 ────────────────────────────────────────────── */
{id:'stan', local:'rota11', classe:'Apostador', arq:'gambler', artigo:'um', nome:'Stan',
 times:[[100,52], [100,52,81], [101,53,82,202], [101,53,82,202,137]], reserva:[109,190],
 abre:'"Cara ou coroa? Tanto faz, a gente luta de qualquer jeito. Eu só gosto de perguntar."',
 volta:'"Coroa. Luta."',
 perde:'"Cara. Sempre dá cara quando eu perco."',
 vence:'"Coroa!"'},
{id:'bernie', local:'rota11', classe:'Operário', arq:'worker', artigo:'um', nome:'Bernie',
 times:[[81,66], [81,66,74], [82,67,75,101], [82,68,76,101,208]], reserva:[100,95],
 abre:'"Intervalo de quinze minutos. Dá pra uma luta, se você for rápid{o|a}."',
 volta:'"Outro intervalo. Outra luta."',
 perde:'"O intervalo acabou e eu perdi. Dia completo."',
 vence:'"Volto pro trabalho feliz."'},
{id:'dave', local:'rota11', classe:'Garoto', arq:'youngster', artigo:'um', nome:'Dave',
 times:[[23,96], [23,96,56], [24,97,57,203], [24,97,57,203,217]], reserva:[216,32],
 abre:'"Penhasco de um lado, mato do outro. Luta no meio, que é mais seguro."',
 volta:'"No meio de novo."',
 perde:'"Eu vou pro lado do mato pensar."',
 vence:'"Viu como o meio é seguro?"',
 numero:{passa:'Dave te dá o número e diz que liga "quando tiver um Pokémon raro", o que ele vai fazer muito.',
   oferece:['revanche','prova'],
   prova:{rotulo:'Perguntar se ele achou o Pokémon raro',
     texto:[
       '"Achei! Quer dizer. Achei que achei. Era um Rattata com a luz batendo."',
       '"Mas um dia eu acho. E aí eu te ligo primeiro."'
     ]}}},

/* ── Rota 12 ────────────────────────────────────────────── */
{id:'andrew', local:'rota12', classe:'Pescador', arq:'fisherman', artigo:'um', nome:'Andrew',
 times:[[129,118,72], [129,118,72,116], [130,119,73,117], [130,119,73,230,224]], reserva:[223,211,170],
 abre:'"Quatro quilômetros de ponte e você resolveu parar logo do meu lado. Espantou o Magikarp. Agora luta."',
 volta:'"Espantou de novo."',
 perde:'"Volto pra vara."',
 vence:'"Fisguei você."',
 numero:{passa:'Andrew anota o número na tampa de uma caixa de isca. "Se o Magikarp grande aparecer, eu te ligo. Um dia ele aparece."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Perguntar se o grande apareceu', limite:4, esperaCap:2,
     texto:[
       '"Não apareceu. Mas eu tenho isca sobrando e você tem cara de quem pesca mal."',
       '"Pega. Não agradece. Pesca."'
     ],
     efeito:d=>{ Estado.darItem('Isca', 3); return [{tipo:'item', texto:'Ele deixou 3× Isca no Centro, embrulhadas em jornal.'}]; }}}},
{id:'luca', local:'rota12', classe:'Roqueiro', arq:'guitarist', artigo:'um', nome:'Luca',
 times:[[100,25], [100,25,81], [101,26,82,125], [101,26,82,125,181]], reserva:[239,179],
 abre:'"Eu toco em cima da água porque o som vai longe. Mas ninguém para pra ouvir. Você parou. Agora luta."',
 volta:'"Música nova. Time novo. Mesmo volume."',
 perde:'"Esse acorde eu errei."',
 vence:'"Solo de guitarra!"'},
{id:'elliot', local:'rota12', classe:'Pescador', arq:'fisherman', artigo:'um', nome:'Elliot',
 times:[[60,98], [60,98,86], [61,99,87,90], [62,99,87,91,226]], reserva:[222,171],
 abre:'"Pescador que não luta não é pescador, é enfeite de ponte. Eu não sou enfeite."',
 volta:'"Continuo não sendo enfeite."',
 perde:'"Hoje eu sou enfeite."',
 vence:'"Enfeite nenhum faz isso."'},

/* ── Rota 13 / 14 / 15 ──────────────────────────────────── */
{id:'sebastian', local:'rota13', classe:'Tratador de Voadores', arq:'bird_keeper', artigo:'um', nome:'Sebastian',
 times:[[21,16], [21,17,163], [22,17,164,84], [22,18,164,85,227]], reserva:[198,83,177],
 abre:'"Vento constante aqui. Os meus adoram. Voam o dia inteiro e ainda sobra força pra lutar."',
 volta:'"O vento virou. Eles cresceram."',
 perde:'"Pousa, pessoal. Pousa."',
 vence:'"Pena por pena, a gente ganhou."',
 numero:{passa:'Sebastian te dá o número e uma pena solta de Pidgeotto como marcador. "Liga quando o vento mudar."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Perguntar do vento', limite:3, esperaCap:3,
     texto:[
       '"Tá virando pro sul. Quando vira pro sul os Pokémon ficam agitados e fogem de repelente."',
       '"Eu mandei uns pra você. Usa na rota comprida."'
     ],
     efeito:d=>{ Estado.darItem('Repelente', 3); return [{tipo:'item', texto:'Ele manda 3× Repelente pelo Centro.'}]; }}}},
{id:'sheila', local:'rota13', classe:'Beldade', arq:'beauty', artigo:'uma', nome:'Sheila',
 times:[[43,69], [44,70,114], [44,70,114,103], [182,71,114,103,192]], reserva:[191,187],
 abre:'"Eu vim pela cerca baixa porque o vento arruma o cabelo. Você veio por quê? Tanto faz. Luta."',
 volta:'"O cabelo tá ótimo hoje. Luta."',
 perde:'"O vento bagunçou tudo."',
 vence:'"O vento tava do meu lado."'},
{id:'jaclyn', local:'rota13', classe:'Treinadora Ás', arq:'ace_trainer_f', artigo:'uma', nome:'Jaclyn', dif:2,
 times:[[29,58], [30,58,111], [30,59,112,131], [31,59,112,131,149]], reserva:[148,121,184],
 abre:'"Eu vou pra Fuchsia com sete insígnias e quero chegar com oito. Você é treino. Nada pessoal."',
 volta:'"Ainda é treino. Agora um pouco pessoal."',
 perde:'"Anotado. Você vai pro caderno."',
 vence:'"Treino bom é treino que rende."',
 numero:{passa:'Jaclyn anota o seu número no caderno dela e te dá o dela. "Pra revanche. Eu faço revanche com todo mundo que me vence. É o caderno."',
   oferece:['revanche','prova'],
   prova:{rotulo:'Contar quantas insígnias você tem',
     texto:d=>{ const n = numInsignias(); return [
       n >= 7 ? `"${n}? Você passou de mim. Vou precisar de um caderno novo."` : `"${n}. Anotado."`,
       '"A gente vai se ver lá em cima. Não pega leve comigo quando for a hora."'
     ]; }}}},
{id:'robert', local:'rota13', classe:'Tratador de Voadores', arq:'bird_keeper', artigo:'um', nome:'Robert',
 times:[[16,21], [17,22,84], [17,22,85,83], [18,22,85,83,178]], reserva:[163,198],
 abre:'"Olha pra cima. Não, mais pra cima. Eles estão lá. Agora olha pra mim, que eles vão descer lutando."',
 volta:'"Eles lembram de você lá de cima."',
 perde:'"Sobe, pessoal. Sobe."',
 vence:'"De cima se vê tudo."'},

/* ── Rota 16 / 17 / 18 ──────────────────────────────────── */
{id:'lao', local:'rota16', classe:'Motoqueiro', arq:'biker', artigo:'um', nome:'Lao',
 times:[[109,23], [109,24,88], [110,24,89,229], [110,24,89,229,169]], reserva:[41,58],
 abre:'"Dezenove quilômetros de reta e você tá a pé no meio dela. Ou é doid{o|a} ou é treinador{|a}. Vamos ver."',
 volta:'"A pé de novo. Doid{o|a} mesmo."',
 perde:'"Treinador{|a}. Não doid{o|a}. Tá."',
 vence:'"Doid{o|a}. Eu sabia."'},
{id:'ruben', local:'rota16', classe:'Motoqueiro', arq:'biker', artigo:'um', nome:'Ruben',
 times:[[88,109], [88,110,23], [89,110,24,215], [89,110,24,215,229]], reserva:[52,198],
 abre:'"Pista é nossa. Pedestre paga pedágio. Pedágio é luta."',
 volta:'"Pedágio de novo."',
 perde:'"Passa sem pagar."',
 vence:'"Pedágio pago."'},
{id:'koji', local:'rota16', classe:'Faixa Preta', arq:'black_belt', artigo:'um', nome:'Koji',
 times:[[66,56], [67,57,236], [67,57,107,106], [68,57,107,106,237]], reserva:[56,236],
 abre:'"Eu corro a ciclovia inteira todo dia, contra o vento. Luta é descanso."',
 volta:'"Corri de novo. Descansa comigo."',
 perde:'"Hah! Bom. Muito bom."',
 vence:'"Vento contra ensina mais que vento a favor."',
 numero:{passa:'Koji te passa o número com uma reverência curta. "Treino, qualquer hora. Eu levanto às cinco."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Chamar pra treinar cedo', limite:3, esperaCap:3,
     texto:[
       '"Cinco da manhã. Ciclovia. Contra o vento. Vem."',
       'Vocês correm, param, repetem. O seu time chega no fim de pé e de pior humor, e mais forte.'
     ],
     efeito:d=>{ const vivos = Estado.timeVivo(); vivos.forEach(p => ganharExp(p, 60 + numInsignias() * 30));
       return [{tipo:'info', texto:'O time inteiro voltou do treino mais duro.'}]; }}}},
{id:'hideo', local:'rota16', classe:'Ciclista', arq:'cyclist', artigo:'um', nome:'Hideo',
 times:[[21,84], [22,84,20], [22,85,20,203], [22,85,20,203,234]], reserva:[161,190],
 abre:'"Eu desço de Celadon a Fuchsia em quarenta minutos. Parei por você. Honra isso."',
 volta:'"Trinta e oito minutos hoje. Parei de novo."',
 perde:'"Perdi o recorde E a luta."',
 vence:'"Recorde e vitória. Dia bom."'},

/* ── Rota 19 / 20 ───────────────────────────────────────── */
{id:'richard', local:'rota19', classe:'Nadador', arq:'swimmer', artigo:'um', nome:'Richard',
 times:[[72,116], [72,117,90], [73,117,91,121], [73,230,91,121,226]], reserva:[120,222],
 abre:'"Eu nado daqui até Seafoam de manhã. Cheguei cedo. Luta comigo que eu não esfrio."',
 volta:'"Nadei de novo. Luta de novo."',
 perde:'"Vou boiar um pouco."',
 vence:'"Mar é meu campo."'},
{id:'anya', local:'rota19', classe:'Nadadora', arq:'swimmer_f', artigo:'uma', nome:'Anya',
 times:[[118,120], [119,120,183], [119,121,184,131], [119,121,184,131,222]], reserva:[170,86],
 abre:'"Aqui é raso. Mais pra frente fica fundo rápido. Luta aqui, no raso, que é mais justo pra você."',
 volta:'"Ainda no raso. Ainda justo."',
 perde:'"Vai pro fundo. Você aguenta."',
 vence:'"Ainda bem que era no raso."',
 numero:{passa:'Anya grita o número de dentro da água três vezes até você decorar.',
   oferece:['revanche','favor'],
   favor:{rotulo:'Perguntar como está o mar', limite:3, esperaCap:3,
     texto:[
       '"Calmo. Quando tá calmo a correnteza traz coisa da praia."',
       '"Eu achei umas garrafas lacradas na areia. Remédio de verdade. Mandei pra você."'
     ],
     efeito:d=>{ Estado.darItem('Hyper Potion', 2); return [{tipo:'item', texto:'Chegou no Centro: 2× Hyper Potion, com areia no rótulo.'}]; }}}},
{id:'douglas', local:'rota19', classe:'Nadador', arq:'swimmer', artigo:'um', nome:'Douglas',
 times:[[60,72], [61,73,98], [62,73,99,131], [62,73,99,131,130]], reserva:[186,211],
 abre:'"Desculpa se eu tô molhado. Na verdade não, é o mar. Luta?"',
 volta:'"Molhado de novo. Luta?"',
 perde:'"Volto pra água."',
 vence:'"Molhado e vitorioso."'},
{id:'connie', local:'rota19', classe:'Nadadora', arq:'swimmer_f', artigo:'uma', nome:'Connie',
 times:[[116,118], [117,119,120], [117,119,121,124], [230,119,121,124,131]], reserva:[238,90],
 abre:'"Todo mundo boia com Pokémon de Água aqui. Eu boio e luto. É mais divertido."',
 volta:'"Boiando e lutando, como sempre."',
 perde:'"Afundei. Brincadeira."',
 vence:'"Boiei melhor."'},

/* ── Ilhas Seafoam ──────────────────────────────────────── */
{id:'shirley', local:'seafoam', classe:'Nadadora', arq:'swimmer_f', artigo:'uma', nome:'Shirley', dif:1,
 times:[[86,90], [86,91,120], [87,91,121,124], [87,91,121,124,131]], reserva:[220,225],
 abre:'"Eu vim ver se a água dentro das pedras tá fria como dizem. Tá. Me aquece com uma luta."',
 volta:'"Ainda fria. Me aquece de novo."',
 perde:'"Esquentei. Obrigada."',
 vence:'"Fria e vitoriosa."'},
{id:'wade', local:'seafoam', classe:'Pescador', arq:'fisherman', artigo:'um', nome:'Wade', dif:1,
 times:[[129,90], [130,90,86], [130,91,87,211], [130,91,87,211,224]], reserva:[170,222],
 abre:'"Ninguém de Fuchsia vem mais aqui. Eu venho. Justamente por isso."',
 volta:'"Ainda venho. Ainda sozinho. Até você chegar."',
 perde:'"Volto pro silêncio."',
 vence:'"O silêncio tava do meu lado."',
 numero:{passa:'Wade te dá o número e diz que só atende de noite, porque de dia está no mar.',
   oferece:['revanche','prova'],
   prova:{rotulo:'Contar onde você esteve',
     texto:[
       '"Eu não pergunto onde. Eu pergunto se voltou inteir{o|a}."',
       '"Voltou. Então tá bom. É só isso que importa pra quem é de mar."'
     ]}}},

/* ── Rota 21 ────────────────────────────────────────────── */
{id:'ronald', local:'rota21', classe:'Pescador', arq:'fisherman', artigo:'um', nome:'Ronald', dif:1,
 times:[[118,129], [119,130,72], [119,130,73,117], [119,130,73,230,226]], reserva:[222,171],
 abre:'"Litoral vazio, vento forte, pescador sozinho. Tá tudo no lugar. Menos você. Luta."',
 volta:'"Você de novo nesse litoral."',
 perde:'"O vento levou."',
 vence:'"O vento trouxe."'},
{id:'barny', local:'rota21', classe:'Mergulhador', arq:'scuba_diver', artigo:'um', nome:'Barny', dif:1,
 times:[[90,98], [90,99,138], [91,99,139,141], [91,99,139,141,226]], reserva:[222,211],
 abre:'"Lá embaixo tem pedra com concha que ninguém viu. Eu vi. Luta comigo que eu te conto."',
 volta:'"Mergulhei de novo. Tem mais concha."',
 perde:'"Não conto então."',
 vence:'"Tá, eu conto: é bonito lá embaixo."'},

/* ── Rota 23 ────────────────────────────────────────────── */
{id:'rolando', local:'rota23', classe:'Treinador Ás', arq:'ace_trainer', artigo:'um', nome:'Rolando', dif:2,
 times:[[58,66,111], [59,67,112], [59,68,112,130], [59,68,112,130,149]], reserva:[248,212,227],
 abre:'"Posto de controle vazio há semanas. Eu fico aqui mesmo assim, de guarda informal. Mostra que você merece passar."',
 volta:'"Mostra de novo."',
 perde:'"Pode passar. De verdade."',
 vence:'"Ainda não. Volta com o time inteiro em pé."',
 numero:{passa:'Rolando te dá o número e bate continência de brincadeira. "Se precisar de alguém do lado lá em cima, eu subo."',
   oferece:['revanche','favor'],
   favor:{rotulo:'Pedir o que ele guarda pra quem sobe', limite:2, esperaCap:3,
     texto:[
       '"Quem sobe precisa voltar. Eu guardo isso pra quem vai subir."',
       '"Usa só quando precisar muito. É o que eu faço."'
     ],
     efeito:d=>{ Estado.darItem('Revive', 2); Estado.darItem('Elixir', 1);
       return [{tipo:'item', texto:'Ele deixou no Centro: 2× Revive e 1× Elixir.'}]; }}}},
{id:'daisuke', local:'rota23', classe:'Faixa Preta', arq:'black_belt', artigo:'um', nome:'Daisuke', dif:2,
 times:[[66,56,106], [67,57,107], [68,57,107,106], [68,57,107,106,237]], reserva:[214,62],
 abre:'"O último trecho antes do Caminho. Quem passa por mim chega lá em cima inteiro."',
 volta:'"Chegou lá em cima? Então volta e passa de novo."',
 perde:'"Hah. Sobe."',
 vence:'"Ainda não."'},
{id:'veronica', local:'rota23', classe:'Treinadora Ás', arq:'ace_trainer_f', artigo:'uma', nome:'Veronica', dif:2,
 times:[[121,35,131], [121,36,131], [121,36,131,149], [121,36,131,149,242]], reserva:[176,184,148],
 abre:'"Oito insígnias no cinto e ainda assim eu treino aqui. Quer saber por quê? Luta."',
 volta:'"Agora você sabe por quê."',
 perde:'"É por isso: porque tem gente como você subindo."',
 vence:'"Porque sempre tem mais."'},

/* ── Caminho da Vitória ─────────────────────────────────── */
{id:'caroline', local:'caminho_vitoria', classe:'Treinadora Ás', arq:'ace_trainer_f', artigo:'uma', nome:'Caroline', dif:3,
 times:[[65,59,131], [65,59,131,148], [65,59,131,149,121], [65,59,131,149,121,242]], reserva:[196,197],
 abre:'"Quatro quilômetros de pedra. Você chegou na metade. A outra metade é comigo."',
 volta:'"A metade de novo. Comigo de novo."',
 perde:'"A outra metade é sua."',
 vence:'"Volta pra metade de baixo."'},
{id:'gregory', local:'caminho_vitoria', classe:'Treinador Ás', arq:'ace_trainer', artigo:'um', nome:'Gregory', dif:3,
 times:[[68,76,112], [68,76,112,208], [68,76,112,208,130], [68,76,112,208,130,248]], reserva:[214,227],
 abre:'"Ninguém passa por aqui sem ter perdido alguma coisa no caminho. Eu vou ver o que você ainda tem."',
 volta:'"Ainda tem coisa. Vamos ver o resto."',
 perde:'"Tem bastante. Sobe."',
 vence:'"Faltou isso."',
 numero:{passa:'Gregory escreve o número numa pedra lisa com carvão e te entrega a pedra.',
   oferece:['revanche','prova'],
   prova:{rotulo:'Contar como foi lá em cima',
     texto:d=>d.flags.campeao_de_kanto
       ? ['"Eu sei como foi. Kanto inteira sabe."', '"Obrigado por ligar mesmo assim. Quem chega lá em cima esquece de quem ficou no Caminho."']
       : ['"Ainda não subiu tudo? Tudo bem. O Caminho espera."', '"Eu tô aqui. Sempre tô."']}}},
{id:'oliver', local:'caminho_vitoria', classe:'Montanhista', arq:'hiker', artigo:'um', nome:'Oliver', dif:3,
 times:[[76,95,68], [76,208,68,232], [76,208,68,232,112], [76,208,68,232,112,248]], reserva:[185,213],
 abre:'"Eu subo e desço esse Caminho há vinte anos e nunca entrei no Planalto. Eu gosto do Caminho. Luta."',
 volta:'"Ainda aqui. Ainda gostando."',
 perde:'"Hohoho! Vai, vai."',
 vence:'"O Caminho escolhe."'}
];

/* rosto de quem luta na estrada: o nome de luta e o nome sozinho.
   E o nome sai do sorteio: ninguém mais em Kanto se chama Joey. */
TREINADORES_ESTRADA.forEach(t => {
  if (typeof NOMES_DA_HISTORIA !== 'undefined') NOMES_DA_HISTORIA.add(t.nome);
  if (typeof RETRATO_POR_NOME === 'undefined') return;
  RETRATO_POR_NOME[nomeDeLuta(t)] = 'trainers/' + t.arq;
  if (!RETRATO_POR_NOME[t.nome]) RETRATO_POR_NOME[t.nome] = 'trainers/' + t.arq;
});
